=== XMLTV/xmltv/xmltv.dtd
<!-- DTD for TV listings

This is a DTD to represent a TV listing.  Rather than breaking the
listing up by channel, it mixes all the channels together.  Data about
a TV programme are stored in the subelements of element 'programme',
but metadata such as when it will be broadcast are stored as
attributes.

Many of the programme details have a 'lang' attribute so that you can
store them in multiple languages or have mixed languages in a single
listing.  This 'lang' should be the two-letter code such as 'en' or
'fr_FR'.  Or you can just leave it out and let your reader take a
guess.

An example XML file for this DTD might look like this:

<tv>
  <programme start="200006031633" channel="ch">
    <title lang="de">blah</title>
    <title lang="en">blah</title>
    <desc lang="de">
       Blah Blah Blah.
    </desc>
    <credits>
      <director>blah</director>
      <actor>a</actor>
      <actor>b</actor>
    </credits>
    <date>19901011</date>
    <country>ES</country>
    <episode-num system="xmltv_ns">2 . 9 . 0/1</episode-num>
    <video>
      <aspect>16:9</aspect>
    </video>
    <rating system="MPAA">PG</rating>
    <star-rating>3/3</star-rating>
  </programme>
  <programme> ... </programme>
  ...
</tv>

With thanks to Gottfried Szing and others for suggestions.

All dates and times in this DTD follow the same format, loosely based
on ISO 8601.  They can be 'YYYYMMDDhhmmss' or some initial
substring, for example if you only know the year and month you can
have 'YYYYMM'.  You can also append a timezone to the end; if no
explicit timezone is given, UT is assumed.  Examples:
'200007281733 BST', '200209', '19880523083000 +0300'.  (BST == +0100.)

Version 0.3.1 (xmltv-0.2.10)

Ed Avis, epa98@doc.ic.ac.uk, 2001-09-14
-->

<!-- The root element, tv.

Date should be the date when the listings were originally produced in
whatever format; if you're converting data from another source, then
use the date given by that source.  The date when the conversion
itself was done is not important.

To indicate the source of the listings, there are three attributes you
can define:

'source-info-url' is a URL describing the data source in
some human-readable form.  So if you are getting your listings from
SAT.1, you might set this to the URL of a page explaining how to
subscribe to their feed.  If you are getting them from a website, the
URL might be the index of the site or at least of the TV listings
section.

'source-info-name' is the link text for that URL; it should
generally be the human-readable name of your listings supplier.
Sometimes the link text might be printed without the link itself, in
hardcopy listings for example.

'source-data-url' is where the actual data is grabbed from.  This
should link directly to the machine-readable data files if possible,
but it's not rigorously defined what 'actual data' means.  If you are
parsing the data from human-readable pages, then it's more appropriate
to link to them with the source-info stuff and omit this attribute.

(There used to be a single attribute 'source' which might or might not
have been a URL; it's left in the DTD so that older files remain valid
but should not be used for new stuff.)

To publicize your wonderful program which generated this file, you can
use 'generator-info-name' (preferably in the form 'progname/version')
and 'generator-info-url' (a link to more info about the program).

(The attribute 'author' is deprecated - most listings don't have an
author in the same way a book does.  If you really are sitting down to
write XMLTV files by hand, you can use source-info-name and
source-info-url to credit yourself.  If you are producing XMLTV files
mechanically, use generator-info-name and generator-info-url.)
-->
<!ELEMENT tv (programme*)>
<!ATTLIST tv date   CDATA #IMPLIED
             source-info-url     CDATA #IMPLIED
             source-info-name    CDATA #IMPLIED
             source-data-url     CDATA #IMPLIED
             generator-info-name CDATA #IMPLIED
             generator-info-url  CDATA #IMPLIED
             source              CDATA #IMPLIED
             author              CDATA #IMPLIED >

<!-- programme - details of a single programme transmission

A show will be exactly the same whether it is broadcast at 18:00 or
19:00, and on whichever channel.  Technical details like broadcast
time don't affect the content of the programme itself, so they are
included as attributes of this element.  Start time and channel are
the two that you must include.

Sometimes VCR programming systems like PDC or VPS have their own
notion of 'start time' which is different from the actual start time,
so there are attributes for that.  In practice, stop time will usually
be the start time of the next programme, but if you can get it more
accurate, good for you.  Similarly, you can specify a code for
Gemstar's Showview or VideoPlus programming systems.

TV listings sometimes have the problem of listing two or more
programmes in the same timeslot, such as 'News; Weather'.  We call
this a 'clump' of programmes, and the 'clumpidx' attribute
differentiates between two programmes sharing the same timeslot and
channel.  In this case News would have clumpidx="0/2" and Weather
would have clumpidx="1/2".  If you don't have this problem, be
thankful!

To do: Some means of indicating breaks between programmes on the same
channel.
-->
<!ELEMENT programme (title+, sub-title*, desc*, credits?, date?,
                     category*, language?, orig-language?, length?,
                     url*, country*, episode-num?, video?, audio?,
                     previously-shown?, premiere?, last-chance?, new?,
                     subtitles*, rating*, star-rating? )>
<!ATTLIST programme start     CDATA #REQUIRED
                    stop      CDATA #IMPLIED
                    pdc-start CDATA #IMPLIED
                    vps-start CDATA #IMPLIED
                    showview  CDATA #IMPLIED
                    videoplus CDATA #IMPLIED
                    channel   CDATA #REQUIRED
                    clumpidx  CDATA "0/1" >

<!-- Programme title, eg 'The Simpsons'. -->
<!ELEMENT title (#PCDATA)>
<!ATTLIST title lang CDATA #IMPLIED>

<!-- Sub-title or episode title, eg 'Datalore'.   Should probably be
called 'secondary title' to avoid confusion with captioning!
-->
<!ELEMENT sub-title (#PCDATA)>
<!ATTLIST sub-title lang CDATA #IMPLIED>

<!-- Description of the programme or episode.

Unlike other elements, long bits of whitespace here are treated as
equivalent to a single space, so you can break lines and write a
pretty-looking paragraph if you wish.
-->
<!ELEMENT desc (#PCDATA)>
<!ATTLIST desc lang CDATA #IMPLIED>

<!-- Credits for the programme.

People are listed in decreasing order of importance; so for example
the starring actors appear first followed by the smaller parts.  As
with other parts of this file format, not mentioning a particular
actor (for example) does not imply that he _didn't_ star in the film -
so normally you'd list only the few most important people.

Adapter can be either somebody who adapted a work for television, or
somebody who did the translation from another language.  Maybe these
should be separate, but if so how would 'translator' fit in with the
'language' element?
-->
<!ELEMENT credits (director*, actor*, writer*, adapter*, producer*,
                   presenter*, commentator*, guest* )>
<!ELEMENT director    (#PCDATA)>
<!ELEMENT actor       (#PCDATA)>
<!ELEMENT writer      (#PCDATA)>
<!ELEMENT adapter     (#PCDATA)>
<!ELEMENT producer    (#PCDATA)>
<!ELEMENT presenter   (#PCDATA)>
<!ELEMENT commentator (#PCDATA)>
<!ELEMENT guest       (#PCDATA)>


<!-- The date the programme or film was finished.  This will probably
be the same as the copyright date.
-->
<!ELEMENT date (#PCDATA)>

<!-- Type of programme, eg 'soap', 'comedy' or whatever the
equivalents are in your language.  There's no predefined set of
categories and it's okay for a programme to belong to several.
-->
<!ELEMENT category (#PCDATA)>
<!ATTLIST category lang CDATA #IMPLIED>

<!-- The language the programme will be broadcast in.  This does not
include the language of any subtitles, but it is affected by dubbing
into a different language.  For example, if a French film is dubbed
into English, language=en and orig-language=fr.

There are two ways to specify the language.  You can use the
two-letter codes such as en or fr, or you can give a name such as
'English' or 'Deutsch'.  In the latter case you might want to use the
'lang' attribute, for example

<language lang="fr">Allemand</language>
-->
<!ELEMENT language (#PCDATA)>
<!ATTLIST language lang CDATA #IMPLIED>

<!-- The original language, before dubbing.  The same remarks as for
'language' apply.
-->
<!ELEMENT orig-language (#PCDATA)>
<!ATTLIST orig-language lang CDATA #IMPLIED>

<!-- The true length of the programme, not counting advertisements or
trailers.  But this does take account of any bits which were cut out
of the broadcast version - eg if a two hour film is cut to 110 minutes
and then padded with 20 minutes of advertising, length will be 110
minutes even though end time minus start time is 130 minutes.
-->
<!ELEMENT length (#PCDATA)>
<!ATTLIST length units (seconds | minutes | hours) #REQUIRED>

<!-- A URL where you can find out more about this programme.  This
might be the official site, or a fan page, whatever you like really.
-->
<!ELEMENT url (#PCDATA)>

<!-- A country where the programme was made or one of the countries in
a joint production.  You can give the name of a country, in which case
you might want to specify the language in which this name is written,
or you can give a two-letter uppercase country code, in which case the
lang attribute should not be given.  For example,

<country lang="en">Italy</country>
<country>GB</country>
-->
<!ELEMENT country (#PCDATA)>
<!ATTLIST country lang CDATA #IMPLIED>

<!-- Episode number

Not the title of the episode, its number or ID.  There are several
ways of numbering episodes, so the 'system' attribute lets you specify
which you mean.

There are two predefined numbering systems, 'xmltv_ns' and
'onscreen'.

xmltv_ns: This is intended to be a general way to number episodes and
parts of multi-part episodes.  It is three numbers separated by dots,
the first is the series or season, the second the episode number
within that series, and the third the part number, if the programme is
part of a two-parter.  All these numbers are indexed from zero, and
they can be given in the form 'X/Y' to show series X out of Y series
made, or episode X out of Y episodes in this series, or part X of a
Y-part episode.  If any of these aren't known they can be omitted.
You can put spaces whereever you like to make things easier to read.

Some examples will make things clearer.  The first episode of the
second series is '1.0.0/1' .  If it were a two-part episode, then the
first half would be '1.0.0/2' and the second half '1.0.1/2'.  If you
know that an episode is from the first season, but you don't know
which episode it is or whether it is part of a multiparter, you could
give the episode-num as '0..'.  Here the second and third numbers have
been omitted.  If you know that this is the first part of a three-part
episode, which is the last episode of the first series of thirteen,
its number would be '0 . 12/13 . 0/3'.  The series number is just '0'
because you don't know how many series there are in total - perhaps
the show is still being made!

The other predefined system, onscreen, is to simply copy what the
programme makers write in the credits - 'Episode #FFEE' would
translate to '#FFEE'.

You are encouraged to use one of these two if possible; if xmltv_ns is
not general enough for your needs, let me know.  But if you want, you
can use your own system and give the 'system' attribute as a URL
describing the system you use.
-->
<!ELEMENT episode-num (#PCDATA)>
<!ATTLIST episode-num system CDATA "onscreen">

<!-- Video details: the sub-elements describe the picture quality as
follows:

present: whether this programme has a picture (no, in the
case of radio stations broadcast on TV or 'Blue'), legal values are
'yes' or 'no'.  Obviously if the value is 'no', the other elements are
meaningless.

colour: 'yes' for colour, 'no' for black-and-white.

aspect: The horizontal:vertical aspect ratio, eg '4:3' or '16:9'.
-->
<!ELEMENT video (present?, colour?, aspect?)>
<!ELEMENT present (#PCDATA)>
<!ELEMENT colour (#PCDATA)>
<!ELEMENT aspect (#PCDATA)>

<!-- Audio details, similar to video details above.

present: whether this programme has any sound at all.

stereo: Description of the stereo-ness of the sound.  Legal values
are currently 'mono' and 'stereo' and 'surround'; others like 'quad'
might be added later.
-->
<!ELEMENT audio (present?, stereo?)>
<!ELEMENT stereo (#PCDATA)>

<!-- When and where the programme was last shown, if known.  Normally
in TV listings 'repeat' means 'previously shown on this channel', but
if you don't know what channel the old screening was on (but do know
that it happened) then you can omit the 'channel' attribute.
Similarly you can omit the 'start' attribute if you don't know when
the previous transmission was (though you can of course give just the
year, etc.).

The absence of this element does not say for certain that the
programme is brand new and has never been screened anywhere before.
-->
<!ELEMENT previously-shown EMPTY>
<!ATTLIST previously-shown start   CDATA #IMPLIED
                           channel CDATA #IMPLIED >

<!-- 'Premiere'.  Different channels have different meanings for this
word - sometimes it means a film has never before been seen on TV in
that country, but other channels use it to mean 'the first showing of
this film on our channel in the current run'.  It might have been
shown before, but now they have paid for another set of showings,
which makes the first in that set count as a premiere!

So this element doesn't have a clear meaning, just use it to represent
where 'premiere' would appear in a printed TV listing.  You can use
the content of the element to explain exactly what is meant, for
example:

<premiere lang="en">
  First showing on national terrestrial TV
</premiere>

If you don't want to do that, just write empty content:

<premiere></premiere>

(I'd like to know how to declare this element so that either #PCDATA
or EMPTY is acceptable content.)
-->
<!ELEMENT premiere (#PCDATA)>
<!ATTLIST premiere lang CDATA #IMPLIED>

<!-- Last-chance.  In a way this is the opposite of premiere.  Some
channels buy the rights to show a movie a certain number of times, and
the first may be flagged 'premiere', the last as 'last showing'.

For symmetry with premiere, you may use the element content to
describe exactly what is meant - it's unlikely to be the last showing
ever!  Otherwise, explicitly put empty content:

<last-chance></last-chance>
-->
<!ELEMENT last-chance (#PCDATA)>
<!ATTLIST last-chance lang CDATA #IMPLIED>

<!-- New.  This is an episode from a new series that has never been
shown on television before - if not worldwide then at least never
before in this country.  After the first episode or programme has been
shown, subsequent ones are no longer 'new'.  Similarly the second
series of an established programme is not 'new'.
-->
<!ELEMENT new EMPTY>

<!-- Subtitles.  These can be either 'teletext' (sent digitally, and
displayed at the viewer's request) or 'onscreen' (superimposed on the
picture and impossible to get rid of).  You can have multiple subtitle
streams to handle different languages.  Language for subtitles is
specified in the same way as for programmes.
-->
<!ELEMENT subtitles (language?)>
<!ATTLIST subtitles type (teletext | onscreen) #IMPLIED>

<!-- Rating.  Various bodies decide on classifications for films -
usually a minimum age you must be to see it.  In principle the same
could be done for ordinary TV programmes.  Because there are many
systems for doing this, you can also specify the rating system used
(which in practice is the same as the body which made the rating).
-->
<!ELEMENT rating (#PCDATA)>
<!ATTLIST rating system CDATA #IMPLIED>

<!-- 'Star rating' - many listings guides award a programme a score as
a quick guide to how good it is.  The value of this element should be
'N / M', for example one star out of a possible five stars would be
'1 / 5'.  Zero stars is also a possible score (and not the same as
'unrated').  You should try to map whatever wacky system your listings
source uses to a number of stars: so for example if they have thumbs
up, thumbs sideways and thumbs down, you could map that to two, one or
zero stars out of two.  Whitespace between the numbers and slash is
ignored.
-->
<!ELEMENT star-rating (#PCDATA)>

<!-- (Why are things like 'stereo', which must be one of a small
number of values, stored as the contents of elements rather than as
attributes?  Because they are data rather than metadata.  Attributes
are used for things like the language or encoding of element contents,
or for programme transmission details.) -->

=== XMLTV/xmltv/t/data-tv_tmdb/Movie-with-unknown-year.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Zed</title>
    <desc>no match as TMDB has no release-date</desc>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Zed</title>
    <desc>no match as TMDB has no release-date</desc>
    <date>2010</date>
  </programme>
</tv>

=== XMLTV/xmltv/t/data-tv_tmdb/Movie-years.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv>
	
  <programme channel="channel0" start="20010829000500 MST">
    <title>The Matrix</title>
    <desc>standard fetch but no urls</desc>
    <date>1999</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>The Matrix</title>
    <desc>match - off by one year</desc>
    <date>2000</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>The Matrix</title>
    <desc>match - off by one year</desc>
    <date>1998</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>The Matrix</title>
    <desc>match - off by two years</desc>
    <date>1997</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>The Matrix</title>
    <desc>no match - off by 3 years</desc>
    <date>1996</date>
  </programme>
  
</tv>

=== XMLTV/xmltv/t/data-tv_tmdb/Title-articles.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv>
  <programme channel="channel0" start="20010829000500 MST">
    <title>The Artist</title>
    <desc>exact match</desc>
    <date>2011</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Artist, The</title>
    <desc>exact match - title is corrected</desc>
    <date>2011</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Le Corbeau</title>
    <desc>exact match</desc>
    <date>1943</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Corbeau, Le</title>
    <desc>exact match - added corrected title</desc>
    <date>1943</date>
  </programme>
</tv>

=== XMLTV/xmltv/t/data-tv_tmdb/Cast-duplicate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Gone with the Wind</title>
    <desc>cast names should not be duplicated</desc>
    <credits>
      <director>Victor Fleming</director>
      <actor>Vivien Leigh</actor>
      <actor>Barbara O'Neil</actor>
    </credits>
    <date>1940</date>
  </programme>
</tv>

=== XMLTV/xmltv/t/data-tv_tmdb/Movies-only.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv>
  <programme channel="channel0" start="20010829000500 MST">
    <title>The Matrix</title>
    <desc>augmented with Director</desc>
    <date>1999</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>The Tonight Show with Jay Leno</title>
    <desc>no augment - --movies-only</desc>
  </programme>
</tv>

=== XMLTV/xmltv/t/data-tv_augment/tv_augment_user_type_15.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">

<tv generator-info-name="tv_augment">
  <channel id="smashhits.net">
    <display-name lang="en">Smash Hits TV</display-name>
  </channel>
  <channel id="travelchannel.co.uk">
    <display-name lang="en">Travel Channel</display-name>
  </channel>
  <channel id="thetravelchannel.co.uk">
    <display-name lang="en">The Travel Channel</display-name>
  </channel>
  <programme start="201607011200 +0100" stop="201607011300 +0100" channel="smashhits.net">
    <title lang="en">UK Top 40</title>
    <desc lang="en">Blah blah blah blah blah.</desc>
    <date>2016</date>
    <category lang="en">Entertainment</category>
    <video>
      <aspect>16:9</aspect>
    </video>
    <subtitles type="teletext">
      <language lang="en">English</language>
    </subtitles>
  </programme>
  <programme start="201607011300 +0100" stop="201607011400 +0100" channel="smashhits.net">
    <title lang="en">UK Top 10</title>
    <desc lang="en">Blah blah blah blah blah.</desc>
    <date>2016</date>
    <category lang="en">Entertainment</category>
    <category lang="en">Music</category>
    <video>
      <aspect>16:9</aspect>
    </video>
    <subtitles type="teletext">
      <language lang="en">English</language>
    </subtitles>
  </programme>
  <programme start="201607011400 +0100" stop="201607011500 +0100" channel="travelchannel.co.uk">
    <title lang="en">A Million Pound Place in the Sun</title>
    <desc lang="en">Blah blah blah blah blah.</desc>
    <date>2016</date>
    <category lang="en">Interests</category>
    <video>
      <aspect>16:9</aspect>
    </video>
    <subtitles type="teletext">
      <language lang="en">English</language>
    </subtitles>
  </programme>
  <programme start="201607011500 +0100" stop="201607011600 +0100" channel="travelchannel.co.uk">
    <title lang="en">A Place in the Sun</title>
    <desc lang="en">Blah blah blah blah blah.</desc>
    <date>2016</date>
    <category lang="en">Travel</category>
    <category lang="en">Interests</category>
    <video>
      <aspect>16:9</aspect>
    </video>
    <subtitles type="teletext">
      <language lang="en">English</language>
    </subtitles>
  </programme>
  <programme start="201607011600 +0100" stop="201607011700 +0100" channel="thetravelchannel.co.uk">
    <title lang="en">A Million Pound Place in the Sun</title>
    <desc lang="en">Blah blah blah blah blah.</desc>
    <date>2016</date>
    <category lang="en">Interests</category>
    <video>
      <aspect>16:9</aspect>
    </video>
    <subtitles type="teletext">
      <language lang="en">English</language>
    </subtitles>
  </programme>
  <programme start="201607011700 +0100" stop="201607011800 +0100" channel="travelchannel.co.uk">
    <title lang="en">A Million Pound Place in the Sun</title>
    <desc lang="en">Blah blah blah blah blah.</desc>
    <date>2016</date>
    <video>
      <aspect>16:9</aspect>
    </video>
    <subtitles type="teletext">
      <language lang="en">English</language>
    </subtitles>
  </programme>
</tv>

=== XMLTV/xmltv/t/data-tv_tmdb/Movie-and-tv.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Wonder Woman</title>
    <desc>regular movie (2009)</desc>
    <date>2009</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Wonder Woman</title>
    <desc>regular movie (1974)</desc>
    <date>1974</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Wonder Woman</title>
    <desc>this wrongly selects the 1974 movie (as off-by-one) - prog is assumed to be a movie (see next test case)</desc>
    <date>1975</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Wonder Woman</title>
    <desc>tv series (1975)</desc>
    <date>1975</date>
    <category>TV Series</category>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Wonder Woman</title>
    <desc>insufficient data to find on tmdb</desc>
  </programme>
</tv>

=== XMLTV/xmltv/t/data-tv_tmdb/Ratings.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tv SYSTEM "xmltv.dtd">
<tv>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Father Ted: A Christmassy Ted</title>
    <desc>add ratings - movie</desc>
    <date>1996</date>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>Father Ted</title>
    <desc>add ratings - tv series</desc>
  </programme>
  <programme channel="channel0" start="20010829000500 MST">
    <title>The Matrix</title>
    <desc>multiple censor classifications</desc>
    <date>1999</date>
  </programme>
</tv>
